### ISSUE TITLE
nn HAL crashes after sometime with TFLite image classifier app on Android things

### ISSUE THREAD

**Issue by anil912001** [intel/nn-hal#1]
I am trying to enable Tensorflow Lite Apps + Movidius on Android Things. To test this I am using a sample Tensorflow lite apk which was given by Google (https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2-tflite/index.html#0)

The app does live image capture + classification. I modified the app to use nnapi “tflite.setUseNNAPI(true)”
I was able to run the app on Joule + Android Things with the Intel_movidius_nn_hal HAL integrated  . It was able to capture and classify objects for a while but the HAL crashes after some time. I have attached the logs here for your reference . The initial part of the logs is when the inference is working .
Can u please help us in fixing this issue ? Let us know if u need more logs from the device.

$logcat | grep VPU

02-02 14:45:09.802  4647  5082 D VPU_LIB : BETA: 1.000000
02-02 14:45:10.664  4647  5082 I ./android.hardware.neuralnetworks@1.0-service-vpudriver: Model Compiling for VPU Driver: completed
02-02 14:45:10.665  4647  5082 D VPU_LIB : Device avilable
02-02 14:45:10.922  4647  5082 D VPU_LIB : Graph Allocated successfully!
02-02 14:45:10.922  4647  5082 D VPU_LIB : Converting input from Float to FP16 Begin
02-02 14:45:10.930  4647  5082 D VPU_LIB : Converting input from Float to FP16 end
02-02 14:45:10.938  4647  5082 D VPU_LIB : Input Tensor Loaded successfully!
02-02 14:45:10.950  4647  5082 D VPU_LIB : Got the Result
02-02 14:45:10.951  4647  5082 D VPU_LIB : Graph Deallocated successfully!
02-02 14:45:10.951  4647  5082 D VPU_LIB : Converting output from FP16 to Float Begin
02-02 14:45:10.951  4647  5082 D VPU_LIB : Converting output from FP16 to Float end
02-02 14:45:10.956  4647  5082 D VPU_LIB : Error code end of the rungraph is : 0
02-02 14:45:11.051  4647  4815 D NCS_GRAPH_COMPILER: Begin to execute on VPU
02-02 14:45:11.052  4647  4815 D NCS_GRAPH_COMPILER: Start execute thread done on VPU
02-02 14:45:11.068  4647  5084 I ./android.hardware.neuralnetworks@1.0-service-vpudriver: Model Compiling for VPU Driver begin
02-02 14:45:11.142  4647  5084 D VPU_LIB : BETA: 1.000000
02-02 14:45:12.048  4647  5084 I ./android.hardware.neuralnetworks@1.0-service-vpudriver: Model Compiling for VPU Driver: completed
02-02 14:45:12.050  4647  5084 D VPU_LIB : Device avilable
02-02 14:45:12.303  4647  5084 D VPU_LIB : Graph Allocated successfully!
02-02 14:45:12.303  4647  5084 D VPU_LIB : Converting input from Float to FP16 Begin
02-02 14:45:12.311  4647  5084 D VPU_LIB : Converting input from Float to FP16 end
02-02 14:45:12.318  4647  5084 D VPU_LIB : Input Tensor Loaded successfully!
02-02 14:45:32.342  4647  5084 E VPU_LIB : NCS could not return result -6
02-02 14:45:32.342  4647  5084 D VPU_LIB : Graph Deallocated successfully!
02-02 14:45:32.430  4647  4647 D NCS_GRAPH_COMPILER: Begin to execute on VPU
02-02 14:45:32.430  4647  4647 D NCS_GRAPH_COMPILER: Start execute thread done on VPU
02-02 14:45:32.444  4647  5090 I ./android.hardware.neuralnetworks@1.0-service-vpudriver: Model Compiling for VPU Driver begin
02-02 14:45:32.529  4647  5090 D VPU_LIB : BETA: 1.000000
02-02 14:45:33.425  4647  5090 I ./android.hardware.neuralnetworks@1.0-service-vpudriver: Model Compiling for VPU Driver: completed
02-02 14:45:33.426  4647  5090 D VPU_LIB : Device avilable
02-02 14:45:43.479  4647  5090 E VPU_LIB : Could not allocate graph for file: -2
02-02 14:45:53.990  4647  5090 D VPU_LIB : NCS device closed
02-02 14:45:53.990  4647  5090 E VPU_LIB : NCS Device found with ErrorCode: 0
02-02 14:45:54.097  4647  5090 E VPU_LIB : Error - Could not open NCS device ErrorCode: -2
02-02 14:45:54.097  4647  5090 E VPU_LIB : Device Unavilable

**Comment by vnsmurthysristi** [comment]
Hello @anil912001 , 

I will look at into this issue, 

Can you Build the app source code is available  https://github.com/vnsmurthysristi/TensorFlowLite_Apps/tree/master/Android/TfLiteSimpleImageClassifier

**Comment by vnsmurthysristi** [comment]
@anil912001 , 

Any update on the above app output?

**Comment by vnsmurthysristi** [comment]
This issue is fixed and will be uploading the patches in 1or 2days

**Comment by vnsmurthysristi** [comment]
The issue is fixed and code is updated please update the code using git pull
