### ISSUE TITLE
can intel/nn-hal be used in other  android platform base on SOCs like QCOM/HUAWEI?

### ISSUE THREAD

**Issue by sunhuchang** [intel/nn-hal#16]

**Comment by sunhuchang** [comment]
is it possible we used NCS on android platform based on ARM SOC?

**Comment by vnsmurthysristi** [comment]
Intel® MKL-DNN Neural Networks HAL - is only for IA CPU not for other architectures 

Intel_movidius_nn_hal should work with ARM also. 
I have never tested it. But it should work. Make sure you have compiled libusb under ROOT_DIR/external/libusb

**Comment by vnsmurthysristi** [comment]
is there any update from the reporter? 
if nothing is required we can close the issue.

**Comment by vnsmurthysristi** [comment]
@sunhuchang can you please update the thread if you need anything please let us know

**Comment by vnsmurthysristi** [comment]
No update from the reporter, hence closing
