### ISSUE TITLE
Support of NCS 2

### ISSUE THREAD

**Issue by emmanuelBerthier** [intel/nn-hal#17]
Hi,

Android support for NCS 1 using nn-hal and running tensorflowLite models is great.

Is there any plan for NCS 2 support?

Thanks.

**Comment by vnsmurthysristi** [comment]
Hello emmanuelBerthier

NCS2 is released recently and it's software is not open sourced yet, we will support once the required software component is opensourced.

**Comment by emmanuelBerthier** [comment]
Thx for the update.

**Comment by vnsmurthysristi** [comment]
ok.. thanks i will close the thread
