### ISSUE TITLE
build error: module defined in both Intel_movidius_nn_hal and vpu-hal2

### ISSUE THREAD

**Issue by jerryrhyu** [intel/nn-hal#3]
build log: 
nn-hal/vpu-hal2/ncsdk2/api/src: MODULE.TARGET.SHARED_LIBRARIES.libmvnc already defined by vendor/bsp/intel/ml/nn-hal/Intel_movidius_nn_hal/ncsdk.

We should name the module version in module to avoid this.

**Comment by vnsmurthysristi** [comment]
with this patch **commit fc7d26ec43149a181d24ca64db2d32b6344f71fe** this issue is fixed
