### ISSUE TITLE
build error: vpu_lib.h is missing

### ISSUE THREAD

**Issue by jerryrhyu** [intel/nn-hal#4]
build log: nn-hal/Intel_movidius_nn_hal/vpuhal/src/vpu_driver/VpuDriver.cpp:32:10: fatal error: 'vpu_lib.h' file not found
#include "vpu_lib.h"

**Comment by vnsmurthysristi** [comment]
with this patch **commit fc7d26ec43149a181d24ca64db2d32b6344f71fe** this issue is fixed
