### ISSUE TITLE
Android GUI Application for testing?

### ISSUE THREAD

**Issue by gsilva2016** [intel/nn-hal#41]
Is there an Android GUI application that can test the Android NNHAL using OpenVINO? There is an example https://github.com/vnsmurthysristi/TensorFlowLite_Apps here but this appears to test using Tensoflow and not OpenVINO inference engine.

**Comment by avaish1** [comment]
have a look at this also ..https://github.com/avaish1/demo

**Comment by brmarkus** [comment]
@avaish1 is this a privat repo? I get an 404 error, either it doesn't exist anymore or it's an internal repo...

**Comment by avaish1** [comment]
you can try now...

**Comment by gsilva2016** [comment]
thanks
