### ISSUE TITLE
Compilation error while compiling NN-HAL

### ISSUE THREAD

**Issue by kumarkan** [intel/nn-hal#9]
Hi,

I see this below compilation error while compiling NN-HAL
external/nn-hal/Intel_movidius_nn_hal/libncs/ncsdk-1.12.00.01/api/src/usb_link_vsc.c:171:2: error: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        memset(&header, 0, sizeof(header));
        ^
external/nn-hal/Intel_movidius_nn_hal/libncs/ncsdk-1.12.00.01/api/src/usb_link_vsc.c:171:2: note: include the header <string.h> or explicitly provide a declaration for 'memset'
external/nn-hal/Intel_movidius_nn_hal/libncs/ncsdk-1.12.00.01/api/src/usb_link_vsc.c:174:2: error: implicitly declaring library function 'strcpy' with type 'char *(char *, const char *)' [-Werror,-Wimplicit-function-declaration]
        strcpy(header.name, name);
        ^
external/nn-hal/Intel_movidius_nn_hal/libncs/ncsdk-1.12.00.01/api/src/usb_link_vsc.c:174:2: note: include the header <string.h> or explicitly provide a declaration for 'strcpy'
2 errors generated.

Issue is fixed after adding adding #include <string.h> to usb_link_vsc.c file.

**Comment by vnsmurthysristi** [comment]
I don't see any compilation error on myside without #include <string.h>
can you give some more details about the setup and environment you are using?

**Comment by vnsmurthysristi** [comment]
fixed now and closed
